//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexFindLib.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings _default = (Settings)
            global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings());

        public static Settings Default => _default;

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchHistory
        {
            get => (string)this["SearchHistory"];
            set => this["SearchHistory"] = value;
        }
    }
}
